services:
  db:
    container_name: koha_db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3300:3306"
    volumes:
      - ./volumes/db_data:/var/lib/mysql

  phpmyadmin:
    container_name: studium_phpmyadmin
    image: digibib/koha:latest
    restart: always
    environment:
      KOHA_INSTANCE: "Catalogo Biblioteca Cedros Norte"
      KOHA_ADMINUSER: admin
      KOHA_ADMINPASS: ${KOHA_ADMIN_PASSWORD}
    ports:
      - 6001:6001
      - 8080:8080
      - 8081:8081

