services:
  db:
    container_name: studium_mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3300:3306"
    volumes:
      - ./volumes/db_data:/var/lib/mysql

  phpmyadmin:
    container_name: studium_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 8081:80