services:
  postgres:
    image: postgres:latest
    restart: always
    user: root
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  videoteca:
    image: 0xeabz/videoteca:main
    restart: always
    ports:
      - 3000:3000  
    environment:
      DB_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}   
      NEXTAUTH_URL: ${NEXTAUTH_URL} 
      OMDB_API_TOKEN: ${OMDB_API_TOKEN} 

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /nas/images/videoteca/volumes/db_data
      o: bind