services:
  postgres:
    container_name: videoteca_postgres
    image: postgres:latest
    restart: always
    user: root
    volumes:
      - ./volumes/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432      

  videoteca:
    container_name: videoteca_ui
    image: 0xeabz/videoteca:main
    restart: always
    ports:
      - 3000:3000
    environment:
      DB_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      OMDB_API_TOKEN: ${OMDB_API_TOKEN}